version: '3.8'

services:
  card-mysql:
    image: mysql:8.0.33
    container_name: card-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345 # test env
      MYSQL_DATABASE: card
      MYSQL_USER: card
      MYSQL_PASSWORD: 12345 # test env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-network

volumes:
  mysql-data:

networks:
  mysql-network:
    driver: bridge
